import{a as m,S as M,i as a}from"./assets/vendor-B5nsgUv9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();m.defaults.baseURL="https://pixabay.com/api/";const v="54657823-2f0cb049819a58dcbd4ca359d",f=15;async function h(t,r=1){const s={key:v,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:f};return(await m.get("",{params:s})).data}const g=document.querySelector(".gallery"),y=document.querySelector(".loader"),p=document.querySelector(".load-more"),R=new M(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function b(t){const r=t.map(({webformatURL:s,largeImageURL:i,tags:e,likes:o,views:c,comments:q,downloads:E})=>`
<li class="gallery-item">
  <a class="gallery-link" href="${i}">
    <img class="gallery-image" src="${s}" alt="${e}" />
  </a>

  <ul class="info">
    <li class="info-item"><b>Likes</b> ${o}</li>
    <li class="info-item"><b>Views</b> ${c}</li>
    <li class="info-item"><b>Comments</b> ${q}</li>
    <li class="info-item"><b>Downloads</b> ${E}</li>
  </ul>
</li>`).join("");g.insertAdjacentHTML("beforeend",r),R.refresh()}function $(){g.innerHTML=""}function L(){y.classList.remove("is-hidden")}function w(){y.classList.add("is-hidden")}function S(){p.classList.remove("is-hidden")}function d(){p.classList.add("is-hidden")}const P=document.querySelector("#search-form"),B=document.querySelector("#load-more");let u="",n=1,l=0;P.addEventListener("submit",D);B.addEventListener("click",H);async function D(t){if(t.preventDefault(),u=new FormData(t.currentTarget).get("searchQuery").trim(),!!u){n=1,l=0,$(),d(),L();try{const s=await h(u,n);if(l=s.totalHits,!s.hits||s.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}b(s.hits),a.success({message:`Hooray! We found ${l} images.`,position:"topRight"});const i=Math.ceil(l/f);n>=i?(d(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):S()}catch{a.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{w(),P.reset()}}}async function H(){n+=1,d(),L();try{const t=await h(u,n);b(t.hits),O();const r=Math.ceil(l/f);if(n>=r){d(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}S()}catch{a.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{w()}}function O(){const t=document.querySelector(".gallery-item");if(!t)return;const{height:r}=t.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
